Repository xitu/front-end-handbook-2018, pull requests merged in 2018-03, with the labels that each got.

#29 learn-from.md - node.md
  learning/learn-from.md
  learning/module-bundlers-loaders.md
  learning/module.md
  learning/multi-device-dev.md
  learning/news-podcasts.md
  learning/node.md
Labels: 校对认领, 正在校对

#14 accessibility
  images/browsers-work.png
  images/statcounter.png
  learning/accessibility.md
  learning/animation.md
  learning/browser-dev-tools.md
  learning/browsers.md
  learning/build.md
Labels: 正在校对

#18 test.md - web-api.md
  learning/test.md
  learning/ui-design-patterns.md
  learning/version-control.md
  learning/web-api.md
Labels: 正在校对

#30 Accessibility.md - browser.md
  tools/accessibility.md
  tools/animation.md
  tools/apps.md
  tools/baas.md
  tools/browsedocs.md
  tools/browser.md
Labels: 正在校对

#31 charting.md - css.md
  tools/charting.md
  tools/cms.md
  tools/code-editor.md
  tools/comm.md
  tools/css.md
Labels: 正在校对

#41 fonts.md -- headless-browsers.md
  learning/fonts.md
  learning/front-end-apps.md
  learning/front-end.md
  learning/headless-browsers.md
Labels: 校对认领

#37 2018.md and README.md
  2018.md
  README.md
Labels: 正在校对

#32 offline.md - react.md
  learning/offline.md
  learning/package-manager.md
  learning/perf.md
  learning/pwa.md
  learning/react.md
Labels: 正在校对

#40 Summary-practice
  SUMMARY.md
  frontendmasters.jpg
  frontendmasters.md
  learning.md
  myIntro.md
  practice.md
Labels: 正在校对

#16 salaries.md - team.md
  practice/salaries.md
  practice/skills.md
  practice/team.md
Labels: 正在校对

#35 perf.md - seo.md
  tools/perf.md
  tools/placeholder.md
  tools/project-hosting.md
  tools/proto.md
  tools/pwa.md
  tools/repo.md
  tools/security.md
  tools/seo.md
Labels: 正在校对

#36 fd-dev-for.md - myth.md
  practice/fd-dev-for.md
  practice/interview-q.md
  practice/jobboards.md
  practice/making-fd.md
  practice/myth.md
Labels: 正在校对

#13 Translate
  images/dns.jpg
  learning/cli.md
  learning/courses.md
  learning/cs.md
  learning/data-api.md
  learning/direct-learning.md
  learning/dns.md
  learning/dom.md
Labels: 正在校对

#42 internet.md -- json.md
  learning/internet.md
  learning/javascript.md
  learning/js-api.md
  learning/json.md
Labels: 正在校对

#17 tech-employed-by-fd.md and types-of-front-end-dev.md
  practice/tech-employed-by-fd.md
  practice/types-of-front-end-dev.md
Labels: 正在校对

#33 db.md - graphics.md
  tools/db.md
  tools/deploy.md
  tools/dev-tools.md
  tools/diagram.md
  tools/dom.md
  tools/error.md
  tools/find-tools.md
  tools/fonts.md
  tools/graphics.md
Labels: 正在校对

#38 state.md - uptime.md
  tools/state.md
  tools/static.md
  tools/svg.md
  tools/task.md
  tools/templates.md
  tools/testing.md
  tools/ui.md
  tools/uptime.md
Labels: 正在校对
